name: Deploy

on:
  push:
    branches:
      - main 
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH and deploy
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "$SSH_PRIVATE_KEY" > keyfile
        chmod 600 keyfile
        mkdir -p ~/.ssh
        cp known_hosts ~/.ssh/known_hosts
        ssh -t -i keyfile ubuntu@ec2-3-138-247-169.us-east-2.compute.amazonaws.com "sudo bash ~/deploy.sh"
# ssh -i todo-app-class.pem ubuntu@ec2-3-138-247-169.us-east-2.compute.amazonaws.com

# ssh-keyscan ec2-3-138-247-169.us-east-2.compute.amazonaws.com >> known_hosts
